-- Add nutrient target columns to Settings table
ALTER TABLE Settings ADD COLUMN FibreTarget REAL;
ALTER TABLE Settings ADD COLUMN CarbsTarget REAL;
ALTER TABLE Settings ADD COLUMN FatTarget REAL;
ALTER TABLE Settings ADD COLUMN SaturatedFatTarget REAL;
ALTER TABLE Settings ADD COLUMN SugarTarget REAL;
ALTER TABLE Settings ADD COLUMN SodiumTarget REAL;

-- Add visibility toggle columns
ALTER TABLE Settings ADD COLUMN ShowProteinOnToday INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Settings ADD COLUMN ShowFibreOnToday INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Settings ADD COLUMN ShowCarbsOnToday INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Settings ADD COLUMN ShowFatOnToday INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Settings ADD COLUMN ShowSaturatedFatOnToday INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Settings ADD COLUMN ShowSugarOnToday INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Settings ADD COLUMN ShowSodiumOnToday INTEGER NOT NULL DEFAULT 0;
